export const FAVORITE_ITEMS_WEATHER_REQUEST = 'FAVORITE_ITEMS_WEATHER_REQUEST'
export const FAVORITE_ITEMS_WEATHER_SUCCESS = 'FAVORITE_ITEMS_WEATHER_SUCCESS'
export const FAVORITE_ITEMS_WEATHER_FAIL = 'FAVORITE_ITEMS_WEATHER_FAIL'
export const FAVORITE_ITEMS_WEATHER_RESET = 'FAVORITE_ITEMS_WEATHER_RESET'

export const FAVORITE_ADD_ITEM = 'FAVORITE_ADD_ITEM'
export const FAVORITE_REMOVE_ITEM = 'FAVORITE_REMOVE_ITEM'

export const FAVORITE_SHOW_ITEM = 'FAVORITE_SHOW_ITEM'
