export const AUTO_COMPLETE_REQUEST = 'AUTO_COMPLETE_REQUEST'
export const AUTO_COMPLETE_SUCCESS = 'AUTO_COMPLETE_SUCCESS'
export const AUTO_COMPLETE_FAIL = 'AUTO_COMPLETE_FAIL'
export const AUTO_COMPLETE_RESET = 'AUTO_COMPLETE_RESET'
